# These are the emojis the bot will look for
# These can also be custom emojis, not just unicode emojis
accepted_emojis = ["â­", "ğŸŒ ", "ğŸŒŸ", "ğŸ’«", "âœ¨", "ğŸ“Œ", "ğŸ“"]

# Number of star reactions required for the message to get put on the starboard
required_stars = 3

# The id for the guild the starboard channel is in
starboard_guild = 0000000000000000000

# The id for the channel to send starboard messages to
starboard_channel = 0000000000000000000
