# These are the emojis the bot will look for
# These can also be custom emojis, not just unicode emojis
accepted_emojis = ["â­", "ğŸŒ ", "ğŸŒŸ", "ğŸ’«", "âœ¨", "ğŸ“Œ", "ğŸ“"]

# Number of star reactions required for the message to get put on the starboard
required_stars = 3

# The various starboard channels the bot wil serve.
# Keys are the guild IDs and the values are the respective starboard channel ID
[starboard_channels]
1111111111111111111 = 11111111111111111111

# The various starboard g the bot wil serve.
# Keys are the guild IDs and the values are the required star reactions
# Optional!
[special_guild_requirements]
1111111111111111111 = 4

# The various starboard channels the bot wil serve.
# Keys are the channel IDs and the values are the required star reactions
# Set to -1 to disbale messages from the channel being put on the starboard
# Optional!
[special_channel_requirements]
1111111111111111111 = 5

# Custom accepted emojis for certain guilds.
# Keys are the guild IDs and the values are lists of strings containing either unicode or custom emojis
# Optional!
[special_guild_emojis]
1111111111111111111 = ["ğŸ"]

